# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs: 
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'descentFrozenHell_buildAndPackAll'
- task: CopyFiles@2
  displayName: Copy server artifacts to staging directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/build/_upload/server/descentfrozenhell'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/server'
- task: CopyFiles@2
  displayName: Copy launcher artifacts to staging directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/build/_upload/multimc-sk'
    Contents: 'descentfrozenhell.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/launcher'
- task: PublishBuildArtifacts@1
  displayName: Publish server artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/server'
    ArtifactName: 'server'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  displayName: Publish launcher artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/launcher'
    ArtifactName: 'server'
    publishLocation: 'Container'