name: Deploy
on:
  release:
    types: [created]
  workflow_dispatch: {}

jobs:
  build:
    name: Build release artifacts
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
      - name: Build Pack (without updating mods)
        run: ./voodoo compile afhtest/latest.voodoo.json5 --no-mod-updates
      - name: Create server package
        run: ./voodoo package afhtest/modpack.meta.json5 server
      - name: Create client package
        run: ./voodoo package afhtest/modpack.meta.json5 voodoo
      - name: Create launcher package
        run: ./voodoo package afhtest/modpack.meta.json5 mmc-voodoo
      - name: Upload server package
        uses: actions/upload-artifact@v2
        with:
          name: server
          path: _upload/server/afhtest_latest
      - name: Upload client package
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: _upload/voodoo
      - name: Upload launcher package
        uses: actions/upload-artifact@v2
        with:
          name: launcher
          path: _upload/multimc-voodoo/afhtest-latest.zip
  deploy-web:
    name: Deploy web server
    needs: ["build"]
    runs-on: ubuntu-20.04
    environment: prod
    steps:
      - name: Download client package
        uses: actions/download-artifact@v2
        with:
          name: client
          path: artifacts/client
      - name: Download launcher package
        uses: actions/download-artifact@v2
        with:
          name: launcher
          path: artifacts/launcher
      - name: Copy client files to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: cdn.avalon.arctarus.co.uk
          key: ${{ secrets.AVALON_SERVER_SSH }}
          username: avalon-deploy
          source: artifacts/client
          target: /var/lib/avalon/cdn/ascent/client
          strip_components: 2
      - name: Copy launcher files to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: cdn.avalon.arctarus.co.uk
          key: ${{ secrets.AVALON_SERVER_SSH }}
          username: avalon-deploy
          source: artifacts/launcher
          target: /var/lib/avalon/cdn/ascent/launcher
          strip_components: 2
  deploy-mc:
    name: Deploy Minecraft server
    needs: ["build"]
    runs-on: ubuntu-20.04
    environment: prod
    steps:
      - name: Download server package
        uses: actions/download-artifact@v2
        with:
          name: server
          path: artifacts/server
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: srv1.avalon.arctarus.co.uk
          key: ${{ secrets.AVALON_SERVER_SSH }}
          username: avalon-deploy
          source: artifacts/server
          target: /var/lib/avalon/mc/ascent/installer
          strip_components: 2
          rm: true
      - name: Extract files on server and restart
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: srv1.avalon.arctarus.co.uk
          key: ${{ secrets.AVALON_SERVER_SSH }}
          username: avalon-deploy
          script: |
            BASE_PATH=/var/lib/avalon/mc/ascent
            doas systemctl stop avalon-mc-ascent
            java -Xmx4G -jar $BASE_PATH/installer/server-installer.jar $BASE_PATH
            ln -sf $BASE_PATH/forge-1.12.2-14.23.5.2854.jar server.jar
            doas systemctl start avalon-mc-ascent
