name: Deploy
on:
  release:
    types: [created]
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2
      - name: Set up Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
      - name: Pack server
        run: |
          mkdir -p _upload/server/deploy
          ./voodoo package afhtest/modpack.meta.json5 server --uploadDir _upload/server/deploy
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: srv1.avalon.arctarus.co.uk
          key: ${{ secrets.AVALON_SERVER_SSH }}
          username: avalon-deploy
          source: _upload/server/deploy/*
          target: /var/lib/avalon/mc/ascent/
