name: Test
on: push

jobs:
  build:
    name: Test pack build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2

      - name: Set up Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64

      - name: Test pack build
        run: ./build.sh
